# kubectl apply -f ./mongo.yaml
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: mysshmongo
  namespace: mykube
  selfLink: /apis/extensions/v1beta1/namespaces/mykube/deployments/mysshmongo
  uid: c0165867-25eb-11ea-9f00-00155d66d536
  resourceVersion: '5491923'
  generation: 1
  creationTimestamp: '2019-12-24T01:21:45Z'
  labels:
    k8s-app: mysshmongo
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: mysshmongo
  template:
    metadata:
      name: mysshmongo
      creationTimestamp: null
      labels:
        k8s-app: mysshmongo
    spec:
      containers:
        - name: mysshmongo
          image: 'biptwjw/mysshmongo:version-0.0.2'
          env:
            - name: qa1BastionHost
              value: 18.191.139.221
            - name: qa1CoreMongoHost
              value: db-core-1
            - name: dev3BastionHost
              value: 18.236.81.75
            - name: dev3SspMongoHost
              value: db-ssp-1
            - name: dev3CoreMongoHost
              value: db-core-1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
            procMount: Default
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2019-12-24T01:21:49Z'
      lastTransitionTime: '2019-12-24T01:21:49Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2019-12-24T01:21:49Z'
      lastTransitionTime: '2019-12-24T01:21:45Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "mysshmongo-7b4d5c9795" has successfully progressed.
